### ISSUE TITLE
how to i call self function inside singleton?

### ISSUE THREAD

**Issue by mike-aungsan** [tarunc/createSingleton#1]
http://stackoverflow.com/questions/13179109/singleton-pattern-in-nodejs-is-it-needed

var mySingleton = createSingleton(function mySingleton() {
  // Describes my singleton class
  var myPrivateVariable = 5;

  this.myPublicFunction = function() {
    // something cool happens
  };

  this.myPublicFunction2 = function() {
    // how to i call myself?
    // how to i call myPublicFunction from here?
  };

});

**Comment by tarunc** [comment]
One way might be to store a variable `self`referring to `this` in the singleton. Your updated code might look like:

``` javascript
var mySingleton = createSingleton(function mySingleton() {
    // Describes my singleton class
    var myPrivateVariable = 5;

    var self = this;

    this.myPublicFunction = function() {
        // something cool happens
    };

    this.myPublicFunction2 = function() {
        // how to i call myself?
        // how to i call myPublicFunction from here?
        self.myPublicFunction();
    };
});
```
